#!/bin/bash

NR_OF_CPUS=$(nproc)
nl=$'\n'

if [[ -z "${TEMOTO_NAMESPACE}" ]]; then
  DATA_PREFIX=''
else
  DATA_PREFIX=${TEMOTO_NAMESPACE}
fi

while sleep 1
do
  jackal_status=$(rostopic echo -n 1 /jackal/robot_manager/robots/jackal/status | egrep "measured_battery:|measured_12v:|user_current:|computer_current:|total_current:")
  jackal_voltage_24=$(echo $jackal_status | awk '{print $2}')
  jackal_voltage_12=$(echo $jackal_status | awk '{print $4}')

  jackal_current_total=$(echo $jackal_status | awk '{print $10}')
  jackal_current_computer=$(echo $jackal_status | awk '{print $8}')
  jackal_current_user=$(echo $jackal_status | awk '{print $6}')

  jackal_power_total=$(echo $jackal_voltage_24*$jackal_current_total | bc -l)
  jackal_power_computer=$(echo $jackal_voltage_12*$jackal_current_computer | bc -l)
  jackal_power_user=$(echo $jackal_voltage_12*$jackal_current_user | bc -l)

  var_pow="power_consumption{system_id=\"$DATA_PREFIX total\"} $jackal_power_total$nl"
  var_pow=$var_pow"power_consumption{system_id=\"$DATA_PREFIX computer\"} $jackal_power_computer$nl"
  var_pow=$var_pow"power_consumption{system_id=\"$DATA_PREFIX user\"} $jackal_power_user$nl"
  
  echo $var_pow

  curl -X POST -H  "Content-Type: text/plain" --data "$var_pow
  " http://localhost:9091/metrics/job/top/instance/machine

done
