{
 "title": "System Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_usage{process=~\".*temoto.*\"}",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage{process=~\".*temoto.*\"}/12",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "targets": [
    { "expr": "avg(cpu_usage)" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "targets": [
    { "expr": "sum(cpu_usage)/12", "legendFormat": "{{process}}" }
   ]
  }
 ]
}