Components:
- component_name: "Realsense d435i 2D camera"
  component_type: "2d_camera"
  package_name: "temoto_ws"
  executable:  "usb_cam_remappable.launch"
  output_topics:
    camera_data_2d: "usb_cam/image_raw"
    camera_info_2d: "usb_cam/camera_info"
  required_parameters:
    frame_id: "camera_link"
    video_device: "/dev/video2"

- component_name: "Realsense d435i"
  component_type: "3d_camera"
  package_name: "temoto_ws"
  executable:  "rs_camera.launch"
  output_topics:
    camera_data_3d: "/camera/depth/color/points"
    camera_info_3d: "/camera/depth/camera_info"
  required_parameters:
    filters: "pointcloud"

- component_name: "My AR tag tracker"
  component_type: "ar_tag_tracker"
  package_name: "temoto_ws"
  executable:  "artag_remappable.launch"
  input_topics:
    camera_info: "camera_info"
    camera_data: "usb_cam/raw"
  output_topics:
    visualization_data: "visualization_marker"
    ar_tag_data: "ar_pose_marker"
  required_parameters:
    frame_id: "camera_link"

- component_name: "AR tag follower algorithm"
  component_type: "ar_cmd_vel_follower"
  package_name: "temoto_ws"
  executable:  "ar_tag_follower.py"
  input_topics:
    ar_tag_data: "ar_pose_marker"
  output_topics:
    cmd_vel: "cmd_vel"


