Components:
- component_name: "PS4 joystick teleop"
  component_type: "joystick_twist"
  package_name: "temoto_ws"
  executable:  "joy_teleop.launch"
  output_topics:
    cmd_vel: "cmd_vel"

- component_name: "String spammer 0"
  component_type: "cs_test_0"
  package_name: "dummy_components"
  executable:  "component_string_0"
  output_topics:
    data_type_0: "cs_0_pub_0"
    data_type_1: "cs_0_pub_1"

- component_name: "String spammer 1"
  component_type: "cs_test_1"
  package_name: "dummy_components"
  executable:  "component_string_1"
  input_topics:
    data_type_0: "cs_1_sub_0"
    data_type_1: "cs_1_sub_1"
  output_topics:
    data_type_2: "cs_1_pub_0"
    data_type_3: "cs_1_pub_1"

- component_name: "String spammer 2_a"
  component_type: "cs_test_2"
  package_name: "dummy_components"
  executable:  "component_string_2_a"
  reliability: 0.8
  input_topics:
    data_type_2: "cs_2_sub_0"
    data_type_3: "cs_2_sub_1"
  output_topics:
    data_type_4: "cs_2_pub_0"
    data_type_5: "cs_2_pub_1"

# - component_name: "String spammer 2_b"
#   component_type: "cs_test_2"
#   package_name: "dummy_components"
#   executable:  "component_string_2_b"
#   reliability: 0.9
#   input_topics:
#     data_type_2: "cs_2_sub_0"
#     data_type_3: "cs_2_sub_1"
#   output_topics:
#     data_type_4: "cs_2_pub_0"
#     data_type_5: "cs_2_pub_1"
