Components:
- component_name: "Realsense d435i 2D camera"
  component_type: "2d_camera"
  package_name: "temoto_ws"
  executable:  "usb_cam_remappable.launch"
  output_topics:
    camera_data_2d: "usb_cam/image_raw"
    camera_info_2d: "usb_cam/camera_info"
  required_parameters:
    frame_id: "camera_link"
    video_device: "/dev/video2"

- component_name: "Realsense d435i"
  component_type: "3d_camera"
  package_name: "temoto_ws"
  executable:  "rs_camera.launch"
  output_topics:
    camera_data_3d: "/camera/depth/color/points"
    camera_info_3d: "/camera/depth/camera_info"
  required_parameters:
    filters: "pointcloud"

- component_name: "String spammer 0"
  component_type: "cs_test_0"
  package_name: "dummy_components"
  executable:  "component_string_0"
  output_topics:
    data_type_0: "cs_0_pub_0"
    data_type_1: "cs_0_pub_1"

- component_name: "String spammer 1"
  component_type: "cs_test_1"
  package_name: "dummy_components"
  executable:  "component_string_1"
  input_topics:
    data_type_0: "cs_1_sub_0"
    data_type_1: "cs_1_sub_1"
  output_topics:
    data_type_2: "cs_1_pub_0"
    data_type_3: "cs_1_pub_1"

- component_name: "String spammer 2_a"
  component_type: "cs_test_2"
  package_name: "dummy_components"
  executable:  "component_string_2_a"
  reliability: 0.8
  input_topics:
    data_type_2: "cs_2_sub_0"
    data_type_3: "cs_2_sub_1"
  output_topics:
    data_type_4: "cs_2_pub_0"
    data_type_5: "cs_2_pub_1"

# - component_name: "String spammer 2_b"
#   component_type: "cs_test_2"
#   package_name: "dummy_components"
#   executable:  "component_string_2_b"
#   reliability: 0.9
#   input_topics:
#     data_type_2: "cs_2_sub_0"
#     data_type_3: "cs_2_sub_1"
#   output_topics:
#     data_type_4: "cs_2_pub_0"
#     data_type_5: "cs_2_pub_1"
