Components:
- component_name: "Realsense d435i"
  component_type: "3d_camera"
  package_name: "temoto_ws"
  executable:  "rs_camera.launch"
  output_topics:
    camera_data_3d: "/camera/depth/color/points"
    camera_info_3d: "/camera/depth/camera_info"
  required_parameters:
    filters: "pointcloud"

- component_name: "Hokuyo 2D LIDAR"
  component_type: "2d_lidar"
  package_name: "temoto_ws"
  executable:  "urg_node_remappable.launch"
  output_topics:
    lidar_data_2d: "scan"
  required_parameters:
    frame_id: "jackal_2d_lidar"
    serial_port: "/dev/ttyACM1"

- component_name: "Ouster OS-1 3D LIDAR"
  component_type: "3d_lidar"
  package_name: "temoto_ws"
  executable:  "os1_remappable.launch"
  output_topics:
    lidar_data_3d: "points_raw"
  required_parameters:
    lidar_address: "10.5.5.55"
    pc_address: "10.5.5.1"
    lidar_frame_name: "os1_link"

- component_name: "Box filter A"
  component_type: "box_filter"
  package_name: "pointcloud_filters"
  executable:  "pointcloud_filter_a"
  reliability: 0.8
  input_topics:
    camera_data_3d: "input"
  output_topics:
    camera_data_3d: "output"

- component_name: "Box filter B"
  component_type: "box_filter"
  package_name: "pointcloud_filters"
  executable:  "pointcloud_filter_b"
  reliability: 0.9
  input_topics:
    camera_data_3d: "input"
  output_topics:
    camera_data_3d: "output"

- component_name: "String spammer 0"
  component_type: "cs_test_0"
  package_name: "dummy_components"
  executable:  "component_string_0"
  output_topics:
    data_type_0: "cs_0_pub_0"
    data_type_1: "cs_0_pub_1"

- component_name: "String spammer 1"
  component_type: "cs_test_1"
  package_name: "dummy_components"
  executable:  "component_string_1"
  input_topics:
    data_type_0: "cs_1_sub_0"
    data_type_1: "cs_1_sub_1"
  output_topics:
    data_type_2: "cs_1_pub_0"
    data_type_3: "cs_1_pub_1"

- component_name: "String spammer 2_a"
  component_type: "cs_test_2"
  package_name: "dummy_components"
  executable:  "component_string_2_a"
  reliability: 0.8
  input_topics:
    data_type_2: "cs_2_sub_0"
    data_type_3: "cs_2_sub_1"
  output_topics:
    data_type_4: "cs_2_pub_0"
    data_type_5: "cs_2_pub_1"

# - component_name: "String spammer 2_b"
#   component_type: "cs_test_2"
#   package_name: "dummy_components"
#   executable:  "component_string_2_b"
#   reliability: 0.9
#   input_topics:
#     data_type_2: "cs_2_sub_0"
#     data_type_3: "cs_2_sub_1"
#   output_topics:
#     data_type_4: "cs_2_pub_0"
#     data_type_5: "cs_2_pub_1"
