processed_pointcloud:
- method:

  - segment_type: "3d_camera"
    output_topic_types:
      - camera_data_3d

  - segment_type: "box_filter"
    input_topic_types:
      - camera_data_3d
    output_topic_types:
      - camera_data_3d

dummy_pipe:
- method:
  - segment_type: "cs_test_0"
    output_topic_types:
      - data_type_0
      - data_type_1

  - segment_type: "cs_test_1"
    input_topic_types:
      - data_type_0
      - data_type_1
    output_topic_types:
      - data_type_2
      - data_type_3

  - segment_type: "cs_test_2"
    input_topic_types:
      - data_type_2
      - data_type_3
    output_topic_types:
      - data_type_4
      - data_type_5